apiVersion: v1
kind: Secret
metadata:
  name: ar-pull-secret
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "7"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "agent-.*"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "agent-.*"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K
