apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: budget-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: http://gitea.gitea.svc.cluster.local/whisperops/whisperops.git
    targetRevision: HEAD
    path: platform/helm/budget-controller
    helm:
      releaseName: budget-controller
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: whisperops-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
