apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kagent
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/kagent-dev/kagent/helm
    chart: kagent
    targetRevision: "0.4.3"
    helm:
      releaseName: kagent
  destination:
    server: https://kubernetes.default.svc
    namespace: kagent-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
