apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: basic-example-templates
  description: A collection of example templates
spec:
  targets:
    - ./basic/template.yaml
    - ./app-with-bucket/template.yaml
    - ./ray-serve/template-ray-serve.yaml
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: basic-organization
  description: Basic organization data
spec:
  targets:
    - ./organization/guests.yaml
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: whisperops-templates
  description: Whisperops dataset-whisperer agent templates
spec:
  targets:
    - ./dataset-whisperer/template.yaml
