apiVersion: v1
kind: Namespace
metadata:
  name: kagent
---
apiVersion: v1
kind: Secret
metadata:
  name: kagent-toolserver-secret
  namespace: kagent
type: Opaque
stringData:
  grafana: disabled
  prometheus: disabled
